# -*- coding: utf-8 -*-
"""Multiple Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFmdXWz8peXbHGlqlUJzJS00eKzNG4mt
"""

# x1, x2, x3
# y = m1*x1 + m2*x2 + m3*x3 + b

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

import math

df = pd.read_csv("/content/homeprices2.csv")
df

median_bedrooms = df.bedrooms.median()

# median_bedrooms = math.floor(df.bedrooms.median())
# median_bedrooms

# df.bedrooms.dropna()

df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

