# -*- coding: utf-8 -*-
"""2. Multiple Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFmdXWz8peXbHGlqlUJzJS00eKzNG4mt
"""

# x1, x2, x3
# y = m1*x1 + m2*x2 + m3*x3 + b

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

# from sklearn import linear_model

# model = linear_model.LinearRegression()

# from sklearn.linear_model import LinearRegression

# model = LinearRegression()

import math

df = pd.read_csv("/content/homeprices2.csv")
df

# df.isnull()
df.isna()

df.isna().sum()

median_bedrooms = df.bedrooms.median()

# median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

# df.bedrooms.dropna()

df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area (sq ft)')
plt.ylabel('price (USD)')
plt.scatter(df.area, df.price, color='red')

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('no of bedrooms')
plt.ylabel('price (USD)')
plt.scatter(df.bedrooms, df.price, color='red')

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('age')
plt.ylabel('price (USD)')
plt.scatter(df.age, df.price, color='red')

reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

reg.coef_

reg.intercept_

reg.predict([[3000, 3, 40]])

reg.predict([[5500, 3, 10]])

