# -*- coding: utf-8 -*-
"""3. Train Test Split MLR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xWLtgtV0GGwaRwOddXTCGmA135hrkbMj
"""

import pandas as pd

df = pd.read_csv("/content/carprices.csv")
df.head()

import matplotlib.pyplot as plt

plt.xlabel('Mileage')
plt.ylabel('Sell Price($)')
plt.scatter(df['Mileage'],df['Sell Price($)'])

plt.xlabel('Age(yrs)')
plt.ylabel('Sell Price($)')
plt.scatter(df['Age(yrs)'],df['Sell Price($)'])

from sklearn.model_selection import train_test_split

X = df[['Mileage','Age(yrs)']]
y = df['Sell Price($)']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

X_test

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

model.predict(X_test)

y_test

model.score(X_test, y_test)

model.score(X_train, y_train)

