# -*- coding: utf-8 -*-
"""4. Logistic Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fX5euafOyxE1gVUfkCUS3w9lmss0L-4T
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

df = pd.read_csv('/content/insurance_data.csv')
df.head()

plt.scatter(df.age,df.bought_insurance,marker='+',color='red')

X_train, X_test, y_train, y_test =train_test_split(df[["age"]],df.bought_insurance,test_size=0.1)

len(X_train)

len(X_test)

model = LogisticRegression()
model.fit(X_train, y_train)

model.predict(X_test)

print(X_test)
print(y_test)

model.score(X_test,y_test)

