# -*- coding: utf-8 -*-
"""5. Multiple Logistic Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKtcF6tsxANpWDsF-P_pwtVyDOA2VDkO
"""

from sklearn.datasets import load_iris

data = load_iris()

data

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data['data'], data['target'], test_size=0.2)

print(len(X_train))
print(len(X_test))

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

y_test

model.predict([[6.2, 2.9, 4.3, 1.3]])

model.score(X_test, y_test)

y_pred = model.predict(X_test)
print(y_pred)
print(y_test)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(3, 3))
sns.heatmap(cm, annot=True)
plt.xlabel('Predicted')
plt.ylabel('Truth')
plt.show()

import pickle

pickle.dump(model, open('model.pkl', 'wb'))

