# -*- coding: utf-8 -*-
"""6. Decision Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SDf6ZJDm7Y0rrARn9smLWEPtgr5qCok-
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

df = pd.read_csv('/content/Titanic-Dataset.csv')
df.head()

df.shape

df.isnull().sum()

median_age = df.Age.median()

df.Age = df.Age.fillna(median_age)

df.isnull().sum()



X = df[['Pclass', 'Sex', 'Age', 'Fare']]
y = df['Survived']

X.head()

le_gender = LabelEncoder()

X['Sex'] = le_gender.fit_transform(X['Sex'])

X.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.head()

print(len(X_train))
print(len(X_test))

model = DecisionTreeClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(y_pred)
print(y_test)

model.score(X_test, y_test)

