# -*- coding: utf-8 -*-
"""Using pickle model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1damBgfJ1MsCWYJ79z-THkKGiRJ_UHX18
"""

import pickle

model = pickle.load(open('/content/model (1).pkl', 'rb'))

model.predict([[5.1, 3.8, 5.5, 1.5]])

