# -*- coding: utf-8 -*-
"""Simple Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Z5Kq4pmXL6VvVqib_Ft_5REYSGKKGOy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv('/content/homeprices1.csv')
df

reg = linear_model.LinearRegression()
reg.fit(df[["area"]], df.price)

reg.predict([[3300]])

reg.coef_

reg.intercept_

# y = mx + b
# price = m*area + b
135.78767123 * 3300 + 180616.43835616432

reg.predict([[5000]])

135.78767123 * 5000 + 180616.43835616432

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel("area (sq ft)")
plt.ylabel("price (US$)")
plt.scatter(df.area, df.price, color="red", marker="+")

reg.predict([[5000], [3300]])

df_areas = pd.read_csv("/content/areas.csv")
df_areas.head(2)

p = reg.predict(df_areas[["area"]])

df_areas["price_p"] = p

df_areas.head()

df_areas.to_csv("prediction.csv", index=False)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel("area (sq ft)")
plt.ylabel("price (US$)")
plt.scatter(df.area, df.price, color="red", marker="+")
plt.scatter(df_areas.area, df_areas.price_p, color="black", marker="+")

